env:
  es6: true
  node: true
  jasmine: true
extends: '@tophat'
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  no-console: 'off'
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
