version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: make -C client install
      - run: make -C service install-ci
      - run: make -C client package
      - persist_to_workspace:
          root: ~/repo
          paths: client/bin/*

  deploy:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on Github"
          command: |
            VERSION=0.0.0
            ls -la /tmp/workspace/*
            ls -la  /tmp/workspace/bin/*
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/workspace/bin/*
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build

