version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: make -C client install
      - run: make -C service install-ci
      - run: make -C client package
      - run: ls -la ./client/bin/*
      - persist_to_workspace:
          root: ./
          paths: client/bin/

  deploy:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: "Publish Release on Github"
          command: |
            VERSION=v0.0.0
            echo $CIRCLE_PROJECT_USERNAME
            echo $CIRCLE_PROJECT_REPONAME
            echo $CIRCLE_SHA1
            echo $VERSION
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/workspace/client/bin/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build

