version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: make -C client install
      - run: make -C service install-ci
      - run: make -C client package
      - store_artifacts:
          path: client/bin/
  deploy:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: ls -la ./artifacts/*
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
        requires:
          - build

