version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
      
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
        make -C client install
        make -C service install-ci
        make -C client package
  deploy:
    docker:
      - image: cibuilds/github:0.10
    branches:
      only:
        - master


