name: lint
description: lints a sub directory (client or service)
inputs:
  project: 
    description: slient of service
    required: true
    default: 'client'
runs:
  using: "composite"
  steps:
    - name: debug
      run: "echo input $INPUT_PROJECT ${{github.event.inputs.project}}"
      shell: bash
    - name: install dependencies 
      run: make -C $INPUT_PROJECT install
      shell: bash
    - name: lint 
      run: make -C $INPUT_PROJECT lint 
      shell: bash
