name: lint
description: lints a sub directory (client or service)
inputs:
  project: 
    description: slient of service
    required: true
    default: 'client'
runs:
  using: "composite"
  steps:
    - name: debug
      run: echo input ${{ inputs.project }}
      shell: bash
    - name: install dependencies 
      run: make -C ${{ inputs.project }} install
      shell: bash
    - name: lint 
      run: make -C ${{ inputs.project }} lint 
      shell: bash
