name: lint
description: lints a sub directory (client or service)
inputs:
  project: 
    description: slient of service
    required: true
runs:
  steps:
    - name: install dependencies 
      run: make -C $INPUT_PROJECT install
    - name: lint 
      run: make -C $INPUT_PROJECT lint 