name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: ./.github/actions/detect-node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Client lint
        uses: ./.github/actions/lint
        with:
          project: client
      - name: Service lint
        uses: ./.github/actions/lint
        with:
          project: service