name: CI

on: [push]

jobs:
  client:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/detect-node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: lint client
        uses: ./.github/actions/lint
        with:
          project: client
      - name: build client 
        uses: ./.github/actions/build
        with:
          project: client
      - name: build docker for client
        run: make -C client build-docker
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: client-artifacts
          path: client/bin
      - name: artifact container
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "tophat/sanity-runner:latest"
  service:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/detect-node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: build service
        uses: ./.github/actions/build
        with:
          project: service
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: service-artifacts
          path: service/artifacts/build
  release-dry-run: 
    needs: [service, client]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
      - name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "tophat/sanity-runner:latest"