name: CI

on: [push, pull_request]

jobs:
  client:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/detect-node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: lint client
        uses: ./.github/actions/lint
        with:
          project: client
      - name: build client 
        uses: ./.github/actions/build
        with:
          project: client
      - name: build docker for client
        run: make -C client build-docker
      - name: lint service
        uses: ./.github/actions/lint
        with:
          project: service
  service:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/detect-node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: build service
        uses: ./.github/actions/build
        with:
          project: service
  semantic-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/detect-node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: make install
      - run: make create-release-package
      - run: make deploy-release-dry